#!/bin/bash

# Will be executed as user "root".

# Name this file "daemon" in your plugin-archive. It will be renamed to NAME
# during installation

loxberryhome=REPLACEINSTALLFOLDER
pluginname=REPLACEFOLDERNAME
lbbackupconfig="/usr/local/etc/raspiBackup.conf"

# Directory/Pluginname fallback for test environment
if [ ! -d $loxberryhome ]; then
	loxberryhome=/opt/loxberry
fi
if [ ! -d $pluginname ]; then
	pluginname=lbbackup
fi


if [ -x /usr/bin/logger ]; then
    /usr/bin/logger "loxberry-plugin-$pluginname - DAEMON Script from LoxBerry Backup Plugin"
fi

# Correct permissions of logs of older versions
chmod a+w $loxberryhome/log/plugins/$pluginname/*

if [ ! -x /usr/local/bin/raspiBackup.sh ]; then
	chmod +x $loxberryhome/data/plugins/$pluginname/raspiBackupInstall.sh
	bash $loxberryhome/data/plugins/$pluginname/raspiBackupInstall.sh -c > $loxberryhome/log/plugins/$pluginname/raspiBackupInstall.log 2>&1
	chmod a+w $lbbackupconfig
	# We have to default raspiBackup to not zip, as we cannot override this for rsync backups (will fail)
	sed -i.bak 's/^\(DEFAULT_ZIP_BACKUP=\).*/\1"0"/' $lbbackupconfig 
fi

# Add LBBackup to sudoers (need root permission)
# Sudoers
sudoversion=2

if [ ! -e $loxberryhome/config/plugins/$pluginname/sudoers.v$sudoversion ]; then
	if [ -x /usr/bin/logger ]; then 
		/usr/bin/logger "loxberry-plugin-$pluginname - Adding sudoers permissions"
	fi
	echo %loxberry ALL = NOPASSWD: /usr/local/bin/raspiBackup.sh > /etc/sudoers.d/$pluginname
	echo %loxberry ALL = NOPASSWD: /usr/local/bin/raspiBackupInstall.sh >> /etc/sudoers.d/$pluginname
	chmod 0440 /etc/sudoers.d/$pluginname
	rm $loxberryhome/config/plugins/$pluginname/sudoers.*
	echo Sudoers V$sudoversion > $loxberryhome/config/plugins/$pluginname/sudoers.v$sudoversion
fi

exit 0
