#!/bin/sh

# Will be executed as user "root".

# Cleanup of lbbackup Plugin
loxberryhome=REPLACELBHOMEDIR
pluginname=REPLACELBPPLUGINDIR

/usr/bin/logger "loxberry-plugin-$pluginname - UNINSTALL Script from LoxBerry Backup Plugin"

# rm -f /etc/sudoers.d/$pluginname
rm -f /usr/local/etc/raspiBackup*.conf*
rm -f /usr/local/bin/raspiBackup*.sh*
rm -f /usr/local/bin/raspiBackupInstall.sh

exit 0
